---
outputs:
- Reveal
title: Become an R Package Developer!
hidden: true
layout: list
weight: 11
output: hugodown::md_document
countdown: true
---

# Package Development

```{r, echo=FALSE}
library("magrittr")
get_pic <- function(id, alt, width) {
  
  info <- httr::GET(
    paste0("https://api.pexels.com/v1/photos/", id),
    httr::add_headers(Authorization = Sys.getenv("PEXELS_KEY"))
  ) %>%
    httr::content()
  download.file(info$src$large, paste0(id, ".jpeg"))
  cat("```{=html}\n")
cat(paste0('{', '{< figure src="',
paste0(id, ".jpeg"),
'" alt="',
alt,
'" caption="Picture by [',
info$photographer,
' on Pexels](',
info$url,
')." width="',
width , '" >}', '}'))
cat("\n```\n")
}
```

```{r repair, results="asis", cache=TRUE, echo=FALSE}
get_pic(id = 132682, alt = "Bike in repair room", 400)
```


---

## Your questions from last time?


---

## Today

- Testing (as opposed to experiments in the console)

- Continuous integration

---

## Further resources

- R packages book, testing chapters: https://r-pkgs.org/testing-basics.html

- https://mtlynch.io/good-developers-bad-tests/

- https://blog.r-hub.io/2020/11/18/testthat-utility-belt/

- https://github.com/r-lib/actions

---

## Questions?

See you at the next package development training?

```{=html}
<iframe src="https://giphy.com/embed/XFpCAWSfTwXh2uSEk2" width="480" height="269" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/moon-et-extra-terrestrial-XFpCAWSfTwXh2uSEk2">via GIPHY</a></p>
```